---
- name: Copy license file
  copy:
    src: "{{ backup_dir }}/non_prod_license/{{ license_file }}"
    dest: "{{ runtime_dir }}/{{ service_name }}/bin/"
    owner: mule
    mode: '0644'

- name: Install the license
  command: ./mule -installLicense {{ runtime_dir }}/{{ service_name }}/bin/{{ license_file }}
  args:
    chdir: "{{ runtime_dir }}/{{ service_name }}/bin/"

- name: Verify the license
  command: ./mule -verifyLicense {{ runtime_dir }}/{{ service_name }}/bin/{{ license_file }}
  args:
    chdir: "{{ runtime_dir }}/{{ service_name }}/bin/"
