- name: Create directories for business groups
  hosts: all
  gather_facts: false
  roles:
    - runtime_install




    # Uncomment to add agent update if needed
    # - name: Update agent for each business group
    #   include_role:
    #     name: agent_update
    #   with_items: "{{ business_groups }}"
    #   loop_control:
    #     loop_var: business_group
